class AppAsset {
  const AppAsset._();

  static const splash = "assets/images/splashScreen.png";
  static const onBoard1 = "assets/images/onBoarding1.png";
  static const onBoard2 = "assets/images/onBoarding2.png";
  static const onBoard3 = "assets/images/onBoarding3.png";
  static const happyScreen = "assets/images/happy_screen.png";
  static const mom = "assets/images/mother.png";
  static const father = "assets/images/father.png";
  static const daugher = "assets/images/daugher.png";
  static const son = "assets/images/son.png";
  static const bigBrother = "assets/images/big_bro.png";
  static const bigSister = "assets/images/big_sister.png";
  static const juniorBrother = "assets/images/junior_bro.png";
  static const juniorSister = "assets/images/junior_sister.png";
  static const uncleMom = "assets/images/uncle_girl.png";
  static const uncleDad = "assets/images/uncle_boy.png";
  static const grandpa = "assets/images/old-man.png";
  static const grandma = "assets/images/old-woman.png";
  static const apple = "assets/images/apple.png";
  static const apricot = "assets/images/apricot.png";
  static const banana = "assets/images/banana.png";
  static const cherry = "assets/images/cherry.png";
  static const grape = "assets/images/grape.png";
  static const melon = "assets/images/melon.png";
  static const peach = "assets/images/peach.png";
  static const pear = "assets/images/pear.png";
  static const plum = "assets/images/plum.png";
  static const raspberry = "assets/images/raspberry.png";
  static const strawberry = "assets/images/strawberry.png";
  static const watermelon = "assets/images/watermelon.png";
  static const acachia = "assets/images/acachia.png";
  static const astra = "assets/images/astra.png";
  static const beet = "assets/images/beet.png";
  static const cabbage = "assets/images/cabbage.png";
  static const carrot = "assets/images/carrot.png";
  static const chamomile = "assets/images/chamomile.png";
  static const chrysanthemum = "assets/images/chrysanthemum.png";
  static const cucumber = "assets/images/cucumber.png";
  static const garlic = "assets/images/garlic.png";
  static const landush = "assets/images/landush.png";
  static const lavender = "assets/images/lavender.png";
  static const lily = "assets/images/lily.png";
  static const nargiss = "assets/images/nargiss.png";
  static const onion = "assets/images/onion.png";
  static const peony = "assets/images/peony.png";
  static const pepper = "assets/images/pepper.png";
  static const poppy = "assets/images/poppy.png";
  static const potato = "assets/images/potato.png";
  static const pumpkin = "assets/images/pumpkin.png";
  static const radish = "assets/images/radish.png";
  static const rose = "assets/images/rose.png";
  static const tomato = "assets/images/tomato.png";
  static const tulip = "assets/images/tulip.png";
  static const zucchini = "assets/images/zucchini.png";

}
